"""Add image_url to Post model

Revision ID: 821b16f17485
Revises: 8343823e4056
Create Date: 2024-07-20 11:18:03.183795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821b16f17485'
down_revision = '8343823e4056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
